### ISSUE TITLE
Add/Copy blog posts from medium to Docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#357]
Should have our blogs also saved on https://docs.giveth.io/blog

**Comment by divine-comedian** [comment]
LIVE 

https://docs.giveth.io/blog

**Comment by laurenluz** [comment]
Am I trippin' or is it only showing some of them? I think it would be great to have also the launch post for trace and io and the "two flavours" one, but I don't see them

**Comment by divine-comedian** [comment]
ah nice catch, there was a setting that was causing it to show only the 5 most recent posts in the sidebar. I fixed it to show all of them, you should see the changes shortly.

**Comment by laurenluz** [comment]
so weird, am I tripping or is the TRACE launch post still missing?

https://docs.giveth.io/blog

**Comment by divine-comedian** [comment]
you were not trippin' I missed it but now I just uploaded it 

https://docs.giveth.io/blog/traceLaunch
