### ISSUE TITLE
Make quick video summaries for donor onboarding course

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#628]
We need summaries for the Youtube Video descriptions for each of these:

https://www.youtube.com/playlist?list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ

**Comment by laurenluz** [comment]
@jfbtheii would you be down to take this one?

**Comment by jfbtheii** [comment]
Yep!

**Comment by jfbtheii** [comment]
I'll have these done tomorrow!

**Comment by jfbtheii** [comment]
https://docs.google.com/document/d/1iJF4z8O6c_vGVYNnDc-e7nRnwEeXKFVE-r70t-v1jwE/edit
Let me know what you think! :)

**Comment by ahmadabugosh** [comment]
Nice work @jfbtheii ! I think we also need to add links as well, since there are several videos where we reference something (especially in the earlier wallet videos and the last video). At the very least, each video should have a link to the section we're talking about in that video, and a link to that section's docs page

**Comment by jfbtheii** [comment]
Added links to everything except for wallet funding. What would be a good link for that? @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Thanks @jfbtheii 

1) For the wallet funding video, I would add links to Coinbase (since that's the example we used in the video), and also this link that we covered at the end of the video (from the Gnosis chain docs:https://www.xdaichain.com/for-users/wallets/metamask/metamask-setup)

2) I also added another video on "How to Donate on Giveth" that we need notes for as well: https://www.youtube.com/watch?v=UlaXjiamHZk&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=4&ab_channel=Giveth

3) They'll probably be at least one more video as well, so I'll keep this issue open until then

Thanks!

**Comment by laurenluz** [comment]
There is one more video! The "Why Giveth" one: https://www.youtube.com/watch?v=kfoyvsPYnrE&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=1

@jfbtheii are you able to finish this one out?

**Comment by ahmadabugosh** [comment]
Done, added all descriptions (along with the missing ones)

**Comment by ahmadabugosh** [comment]
If you're fine with them, feel free to close this issue @laurenluz

**Comment by laurenluz** [comment]
I just made suggestions in the doc. The "Why giveth?" summary is still missing.

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz I added a Why Giveth summary.

https://docs.google.com/document/d/1iJF4z8O6c_vGVYNnDc-e7nRnwEeXKFVE-r70t-v1jwE/edit

 I kept it generic (not mentioning the course), since I think this video could be shared independently with people outside of the playlist

**Comment by laurenluz** [comment]
Sounds good! I made small suggestions, I think it's good to put these up now

**Comment by ahmadabugosh** [comment]
Done! Closing this issue
